name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        

jobs:
  Export-solution-Feedback:
    uses: ./.github/workflows/export-and-branch-solution.yml
    with:
      #You can specify the solution name here
      solution_name: BuchausleihenVerwaltung
      solution_exported_folder: out/exported/
      solution_folder: out/solutions/
      solution_target_folder: solutions/
      BUILD_ENVIRONMENT_URL: https://org4efa06c7.crm4.dynamics.com/
      CLIENT_ID: f6a882b0-ec07-4481-a9d8-518de31158e7
      TENANT_ID: 71b0211b-f2c2-4978-9b00-0e1f64e22567 
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}

  Release-solution-Feedback:
    needs: [ Export-solution-Feedback ]
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: BuchausleihenVerwaltung
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://org4efa06c7.crm4.dynamics.com/
      PRODUCTION_ENVIRONMENT_URL: https://org46e6cc0d.crm4.dynamics.com
      CLIENT_ID: f6a882b0-ec07-4481-a9d8-518de31158e7
      TENANT_ID: 71b0211b-f2c2-4978-9b00-0e1f64e22567    
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
